config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"

  get 'sessions/create'

  get 'sessions/destroy'

  get '/map', to: 'map#index'

  get 'login' => 'login#index'

  namespace :api do
    resources :spaces
    
  end

  resources :bands
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/index.html.erb
<div class='container'>
  <div class='row welcome-home'>
    <div class='welcome col-md-4 text-center'>
      <h2>Sign Up</h2>
      <p>Make a profile, find your friends.</p>
      <%= link_to 'Band page', bands_path, class: 'btn btn-danger' %>
    </div>
    <div class='col-md-4 intro'>
      <h2>Hello</h2>
      <p id="welcome">What if there was a wiki for show spaces across the united states for bands and musicians to easily tour cities. This is for the musicians that have to ask around and rush to find shows in the 11th hour of planning a tour. No bookers, no managers, no agents. Just people playing music and sharing their art on the road, sprinkled around cities. This is a transparent network of musicians across the us aimed at actively participating in a way to support each other on the road. Update show space information for each city. Find your friends. This is a crowd sourced, living, changing database of DIY venues and show spaces.</p>
      <%= link_to 'Home', root_path, class: 'btn btn-danger welcome text-center' %>
    </div>
    <div class='welcome col-md-4 text-center'>
      <h2>Map</h2>  
      <p>Find DIY venues and show spaces</p>
      <%= link_to 'Map', map_path, class: 'btn btn-danger' %>
    </div>
  </div> 

  <div>
    <img src="">
  </div>
</div> 